ClapTrap: {
    shape: class

    -name_: "[]string"
    -hit_points_: "int"
    -enegy_points_: "int"
    -attack_damage_: "int"

    
    +attack(target string): (void)
    +take_damage(amount uint): (void)
    +be_reparied(amount uint): (void)
}